### ISSUE TITLE
drupal/address 1.x-dev -> no matching package found.

### ISSUE THREAD

**Issue by rootical** [INsReady/docker-drupal-commerce#3]
Running into this issue during `docker build .` command inside 8.1 as well as dev. 
Could you please point out what I am doing wrong?

```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
Problem 1
    - Installation request for drupal/commerce 8.2.x-dev -> satisfiable by drupal/commerce[8.2.x-dev].
    - drupal/commerce 8.2.x-dev requires drupal/address 1.x-dev -> no matching package found.
```

**Comment by skyred** [comment]
No. you didn't do anything wrong. According to the build history: https://hub.docker.com/r/insready/drupal-commerce/builds/ . There was a change happened about 16 days ago, which broke the current build. 

You can either download the latest success build from 16 days ago:https://hub.docker.com/r/insready/drupal-commerce/

Or, wait for a fix. (I am currently spending my time on a theme project at the moment.) So, I won't look into Drupal Commerce until its next alpha release happens. If you find a fix first, please let me know. (I assume this should be a simple change)

**Comment by skyred** [comment]
Drupal Commerce 8.x-2.0-beta1 was released. So, I took the chance to fix the builds.
